Add new useGitHubStatus property
btkelly/gnag pull request #211
Opened 2019-02-02 01:32 UTC by IlmazGumerov

This is a very good library, which I really like.

I and most of my friends use Circleci, where there is a free mode. In Circleci there is a very convenient workflow, where the next task does not start until the dependent ones are not success. But gnagReport completes the task successfully even if there are violations. Because of this, it can deploy, but the code is not correct.
I added an additional parameter to ***useGitHubStatus***, which is true by default.
If ***useGitHubStatus*** is false and the ***failOnError*** is enabled, the job will fail

If you have questions and suggestions, write:)

2019-02-12 13:08 UTC, IlmazGumerov commented
Hey hey hey!

2019-02-12 14:14 UTC, btkelly requested changes
Sorry I was a little late to respond 😬and thanks for the contributions! One minor change request otherwise this looks good. Once this is all set I can do a point release to make this available.

2019-02-12 14:14 UTC, btkelly commented on README.md
> +    useGitHubStatuses(true)
I'm thinking this property should belong inside the `github` block as it's a setting specific to GitHub and not the entire `Gnag` plugin. I'm thinking to the future if we ever add support for other source repositories such as GitLab.

2019-02-12 14:14 UTC, btkelly commented on plugin/src/main/groovy/com/btkelly/gnag/tasks/GnagReportTask.java
> +          throw new StopExecutionException(gitHubStatusType.getDescription());
This is cool! I didn't even know Gradle had a special exception to stop the task but not actually fail it. 🥇

2019-02-13 14:12 UTC, btkelly commented
Looks great! Thanks for the addition @IlmazGumerov

2019-02-13 14:12 UTC, merged

2019-02-13 14:19 UTC, btkelly commented
New point release out with this included, version `2.2.2`